CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallets (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  gems INTEGER NOT NULL DEFAULT 500,
  coins INTEGER NOT NULL DEFAULT 1000,
  fruit INTEGER NOT NULL DEFAULT 0,
  last_daily_claim BIGINT NOT NULL DEFAULT 0,
  daily_streak INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(40) NOT NULL,
  gems_delta INTEGER NOT NULL DEFAULT 0,
  coins_delta INTEGER NOT NULL DEFAULT 0,
  fruit_delta INTEGER NOT NULL DEFAULT 0,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_id_created_at
  ON transactions (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS gacha_profiles (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  rate_common NUMERIC NOT NULL DEFAULT 0.595,
  rate_rare NUMERIC NOT NULL DEFAULT 0.25,
  rate_epic NUMERIC NOT NULL DEFAULT 0.10,
  rate_legendary NUMERIC NOT NULL DEFAULT 0.04,
  rate_mythic NUMERIC NOT NULL DEFAULT 0.015,
  pity_threshold INTEGER NOT NULL DEFAULT 50,
  pity_count INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
